"""Matplotlib rendering — static figures, the analysis panel, and animated GIF/MP4.

The README's media is *generated by the tool*, not hand-made. The
aesthetic mirrors the web app's tactical console: deep near-black navy,
phosphor-cyan interceptor, warm amber target, white for the moment of truth.

This module is import-light: matplotlib is only imported inside functions so the engine
core stays usable without it.
"""

from __future__ import annotations

import math
from pathlib import Path

from .engagement import Result

# Tactical palette (colorblind-safe cyan/amber pairing; never red/green alone).
BG = "#070b14"
PANEL = "#0c1322"
GRID = "#16233a"
CYAN = "#37e0e6"      # interceptor
AMBER = "#ffb454"     # target
WHITE = "#f4f8ff"
RED = "#ff5d5d"       # danger only
MUTED = "#7c8aa5"


def _style(ax) -> None:
    ax.set_facecolor(PANEL)
    for spine in ax.spines.values():
        spine.set_color(GRID)
    ax.tick_params(colors=MUTED, labelsize=8)
    ax.grid(True, color=GRID, linewidth=0.6, alpha=0.7)
    ax.xaxis.label.set_color(MUTED)
    ax.yaxis.label.set_color(MUTED)
    ax.title.set_color(WHITE)


def _g_clip(values, cap_mult: float = 2.0, floor: float = 60.0):
    """Clip commanded-g traces so the terminal 1/R^2 singularity doesn't wreck scaling."""
    cap = max(floor, cap_mult * floor)
    return [max(-cap, min(cap, v)) for v in values]


def static_plot(result: Result, path: str | Path, dpi: int = 130) -> Path:
    """A single framed trajectory figure with periodic LOS lines and the verdict."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    t = result.telemetry
    xm, ym = t.column("x_m"), t.column("y_m")
    xt, yt = t.column("x_t"), t.column("y_t")

    fig, ax = plt.subplots(figsize=(9, 6))
    fig.patch.set_facecolor(BG)
    _style(ax)

    # periodic LOS "ghosts" (the constant-bearing overlay)
    n = len(xm)
    for i in range(0, n, max(1, n // 14)):
        ax.plot([xm[i], xt[i]], [ym[i], yt[i]], color=MUTED, lw=0.5, alpha=0.35, zorder=1)

    ax.plot(xm, ym, color=CYAN, lw=2.0, label="Interceptor", zorder=3)
    ax.plot(xt, yt, color=AMBER, lw=2.0, label="Target", zorder=3)
    ax.scatter([xm[0]], [ym[0]], color=CYAN, s=40, zorder=4)
    ax.scatter([xt[0]], [yt[0]], color=AMBER, s=40, zorder=4)

    # intercept point
    color = WHITE if result.hit else RED
    ax.scatter([xm[-1]], [ym[-1]], color=color, s=120, marker="*", zorder=5)

    ax.set_aspect("equal", adjustable="datalim")
    ax.set_xlabel("downrange  x  [m]")
    ax.set_ylabel("crossrange  y  [m]")
    ax.set_title(f"{result.scenario_name}   —   {result.law.upper()}  N={result.N:g}")

    verdict = (
        f"{result.verdict}   miss={result.miss_distance:.2f} m   "
        f"peak g={result.peak_g:.1f}   t={result.t_flight:.2f} s   seed={result.seed}"
    )
    ax.text(
        0.5, 0.04, verdict, transform=ax.transAxes, ha="center",
        color=color, fontsize=11, fontweight="bold",
        bbox=dict(boxstyle="round,pad=0.4", fc=PANEL, ec=color, alpha=0.9),
    )
    leg = ax.legend(loc="upper right", framealpha=0.2, fontsize=8)
    for txt in leg.get_texts():
        txt.set_color(WHITE)

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=dpi, facecolor=BG)
    plt.close(fig)
    return path


def analysis_panel(result: Result, path: str | Path, dpi: int = 130) -> Path:
    """The post-engagement analyst panel: the plots an analyst draws."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    t = result.telemetry
    time = t.column("t")
    fig, axs = plt.subplots(2, 2, figsize=(11, 7))
    fig.patch.set_facecolor(BG)
    for ax in axs.flat:
        _style(ax)

    # (0,0) commanded vs achieved g
    ax = axs[0, 0]
    ax.plot(time, _g_clip(t.column("g_cmd")), color=MUTED, lw=1.0, label="commanded")
    ax.plot(time, t.column("g_ach"), color=CYAN, lw=1.6, label="achieved")
    ax.set_title("Acceleration  [g]")
    ax.set_xlabel("t [s]")
    _legend(ax)

    # (0,1) LOS rate (true vs measured)
    ax = axs[0, 1]
    ax.plot(time, [math.degrees(v) for v in t.column("lambda_dot")], color=AMBER, lw=1.4, label="true λ̇")
    ax.plot(time, [math.degrees(v) for v in t.column("lambda_dot_meas")], color=CYAN, lw=1.0, alpha=0.8, label="measured λ̇")
    ax.axhline(0, color=WHITE, lw=0.6, alpha=0.5)
    ax.set_title("LOS rate  [deg/s]   (driven to zero)")
    ax.set_xlabel("t [s]")
    _legend(ax)

    # (1,0) separation / range
    ax = axs[1, 0]
    ax.plot(time, t.column("R"), color=CYAN, lw=1.6)
    ax.axhline(result.lethal_radius, color=RED, lw=0.8, ls="--", alpha=0.8, label="lethal radius")
    ax.set_title("Range to go  [m]")
    ax.set_xlabel("t [s]")
    ax.set_yscale("log")
    _legend(ax)

    # (1,1) missile vs target g
    ax = axs[1, 1]
    ax.plot(time, t.column("g_ach"), color=CYAN, lw=1.6, label="interceptor")
    ax.plot(time, [v / 9.80665 for v in t.column("a_t")], color=AMBER, lw=1.6, label="target")
    ax.set_title("Lateral g:  interceptor vs target")
    ax.set_xlabel("t [s]")
    _legend(ax)

    fig.suptitle(
        f"{result.scenario_name}  —  {result.verdict}  "
        f"miss={result.miss_distance:.2f} m  seed={result.seed}",
        color=WHITE, fontsize=13,
    )
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(path, dpi=dpi, facecolor=BG)
    plt.close(fig)
    return path


def _legend(ax) -> None:
    leg = ax.legend(loc="best", framealpha=0.15, fontsize=7)
    if leg:
        for txt in leg.get_texts():
            txt.set_color(WHITE)


def animate(
    result: Result,
    path: str | Path,
    fps: int = 30,
    n_frames: int = 160,
    dpi: int = 110,
    trail: int = 40,
) -> Path:
    """Render an animated GIF (``.gif``) or MP4 (``.mp4``) of the engagement.

    A fixed number of frames is sampled from the telemetry so the duration is sane
    regardless of the 1 kHz physics. Output format is inferred from the suffix.
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.animation import FFMpegWriter, FuncAnimation, PillowWriter

    t = result.telemetry
    xm, ym = t.column("x_m"), t.column("y_m")
    xt, yt = t.column("x_t"), t.column("y_t")
    R = t.column("R")
    g_ach = t.column("g_ach")
    ld = t.column("lambda_dot")
    n = len(xm)
    step = max(1, n // n_frames)
    idx = list(range(0, n, step))
    if idx[-1] != n - 1:
        idx.append(n - 1)

    fig, ax = plt.subplots(figsize=(8, 6))
    fig.patch.set_facecolor(BG)
    _style(ax)
    pad = 0.08 * max(max(xt) - min(xm), max(yt + ym) - min(yt + ym), 1.0)
    ax.set_xlim(min(min(xm), min(xt)) - pad, max(max(xm), max(xt)) + pad)
    allys = ym + yt
    ax.set_ylim(min(allys) - pad, max(allys) + pad)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("downrange  [m]")
    ax.set_ylabel("crossrange  [m]")
    ax.set_title(f"{result.scenario_name}  —  {result.law.upper()} N={result.N:g}")

    (los_line,) = ax.plot([], [], color=MUTED, lw=1.0, alpha=0.8, zorder=2)
    (m_trail,) = ax.plot([], [], color=CYAN, lw=2.0, zorder=3)
    (t_trail,) = ax.plot([], [], color=AMBER, lw=2.0, zorder=3)
    (m_dot,) = ax.plot([], [], "o", color=CYAN, ms=7, zorder=4)
    (t_dot,) = ax.plot([], [], "o", color=AMBER, ms=7, zorder=4)
    hud = ax.text(
        0.02, 0.97, "", transform=ax.transAxes, va="top", ha="left",
        color=WHITE, fontsize=9, family="monospace",
        bbox=dict(boxstyle="round,pad=0.3", fc=PANEL, ec=GRID, alpha=0.85),
    )

    def init():
        for art in (los_line, m_trail, t_trail, m_dot, t_dot):
            art.set_data([], [])
        hud.set_text("")
        return los_line, m_trail, t_trail, m_dot, t_dot, hud

    def update(frame_i):
        k = idx[frame_i]
        lo = max(0, k - trail * step)
        m_trail.set_data(xm[lo:k + 1], ym[lo:k + 1])
        t_trail.set_data(xt[lo:k + 1], yt[lo:k + 1])
        m_dot.set_data([xm[k]], [ym[k]])
        t_dot.set_data([xt[k]], [yt[k]])
        los_line.set_data([xm[k], xt[k]], [ym[k], yt[k]])
        hud.set_text(
            f"t   {t.column('t')[k]:6.2f} s\n"
            f"R   {R[k]:7.0f} m\n"
            f"Vc  {t.column('V_c')[k]:6.0f} m/s\n"
            f"λ̇   {math.degrees(ld[k]):6.2f} °/s\n"
            f"g   {g_ach[k]:6.1f}"
        )
        if frame_i == len(idx) - 1:
            color = WHITE if result.hit else RED
            m_dot.set_color(color)
            ax.scatter([xm[k]], [ym[k]], color=color, s=180, marker="*", zorder=6)
            hud.set_text(
                hud.get_text() + f"\n{result.verdict}  miss {result.miss_distance:.2f} m"
            )
        return los_line, m_trail, t_trail, m_dot, t_dot, hud

    anim = FuncAnimation(
        fig, update, frames=len(idx), init_func=init, blit=False, interval=1000 / fps
    )

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix.lower() == ".mp4":
        writer = FFMpegWriter(fps=fps, bitrate=2400)
    else:
        writer = PillowWriter(fps=fps)
    anim.save(str(path), writer=writer, dpi=dpi, savefig_kwargs={"facecolor": BG})
    plt.close(fig)
    return path
